package com.autohotkey.runconfig.core

import com.autohotkey.util.AhkConstants
import com.autohotkey.util.AhkIcons
import com.intellij.execution.configurations.ConfigurationFactory
import com.intellij.execution.configurations.RunConfiguration
import com.intellij.execution.configurations.SimpleConfigurationType
import com.intellij.execution.configurations.runConfigurationType
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.NotNullLazyValue

/**
 * Creates the Ahk run config type that can be selected when choosing a run config template. The factory is generated by
 * the super class.
 *
 * (This is registered in plugin.xml)
 */
class AhkRunConfigType : SimpleConfigurationType(
    id = ID,
    name = AhkConstants.LANGUAGE_NAME,
    icon = NotNullLazyValue.createValue { AhkIcons.EXE },
) {
    val factory: ConfigurationFactory get() = configurationFactories.single()

    companion object {
        const val ID = "AhkRunConfiguration"

        fun getInstance() = runConfigurationType<AhkRunConfigType>()
    }

    override fun createTemplateConfiguration(project: Project): RunConfiguration {
        return AhkRunConfig(project, this, AhkConstants.LANGUAGE_NAME)
    }
}
