[versions]
# libraries
junit4 = "4.+"
junit = "5.+"
kotest = "6.+"
mockk = "1.14.+"

# plugins
changelog = "2.+"
intelliJPlatform = "2.10.+"
grammarKit = "2022.3.+"
kotlin = "2.2.+"
ktlint = "12.+"
qodana = "0.1.+"

[libraries]
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[bundles]
kotest = ["kotest-runner", "kotest-assertions"]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
grammarKit = { id = "org.jetbrains.grammarkit", version.ref = "grammarKit" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
